@IsTest
public with sharing class lwcCustomMetadataCRUDControllerTest {
    @IsTest
    public static void lwcCustomMetadataCRUDControllerTest() {
        lwcCustomMetadataCRUDController.getGlobalCustomMetadataUnprotectedRecordSubscriberField();
        lwcCustomMetadataCRUDController.getGlobalCustomMetadataUnprotectedRecordDeveloperField();
        lwcCustomMetadataCRUDController.getGlobalCustomMetadataProtectedRecordSubscriberField();
        lwcCustomMetadataCRUDController.getGlobalCustomMetadataProtectedRecordDeveloperField();
        lwcCustomMetadataCRUDController.getNSCustomMetadataUnprotectedRecordSubscriberField();
        lwcCustomMetadataCRUDController.getNSCustomMetadataUnprotectedRecordDeveloperField();
        lwcCustomMetadataCRUDController.getNSCustomMetadataProtectedRecordSubscriberField();
        lwcCustomMetadataCRUDController.getNSCustomMetadataProtectedRecordDeveloperField();
        lwcCustomMetadataCRUDController.getMPCustomMetadataProtectedRecordUpgradableField();
        lwcCustomMetadataCRUDController.getMPCustomMetadataProtectedRecordSubscriberField();
        lwcCustomMetadataCRUDController.getMPCustomMetadataUnprotectedRecordUpgradableField();
        lwcCustomMetadataCRUDController.getMPCustomMetadataUnprotectedRecordSubscriberField();

        lwcCustomMetadataCRUDController.updateGlobalCustomMetadataUnprotectedRecordSubscriberField();
        lwcCustomMetadataCRUDController.updateGlobalCustomMetadataUnprotectedRecordDeveloperField();
        lwcCustomMetadataCRUDController.updateGlobalCustomMetadataProtectedRecordSubscriberField();
        lwcCustomMetadataCRUDController.updateGlobalCustomMetadataProtectedRecordDeveloperField();
        lwcCustomMetadataCRUDController.updateNSCustomMetadataUnprotectedRecordSubscriberField();
        lwcCustomMetadataCRUDController.updateNSCustomMetadataUnprotectedRecordDeveloperField();
        lwcCustomMetadataCRUDController.updateNSCustomMetadataProtectedRecordSubscriberField();
        lwcCustomMetadataCRUDController.updateNSCustomMetadataProtectedRecordDeveloperField();
        lwcCustomMetadataCRUDController.updateMPCustomMetadataProtectedRecordUpgradableField();
        lwcCustomMetadataCRUDController.updateMPCustomMetadataProtectedRecordSubscriberField();
        lwcCustomMetadataCRUDController.updateMPCustomMetadataUnprotectedRecordUpgradableField();
        lwcCustomMetadataCRUDController.updateMPCustomMetadataUnprotectedRecordSubscriberField();
    }
}